### ISSUE TITLE
Refactoring on secret breaks helm upgrade at same version 3.2.0 or helm install on top of pre-existing PVCs

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#112]
I had an instance provisioned with the last commit I got merged a few days before #109 was merged. On an upgrade operation against the current master you get:

```
$ kubectl get pods
NAME                                                   READY   STATUS                       RESTARTS   AGE
lopsided-wildebeest-galaxy-job-0-596c85969c-nwwlz      0/1     Init:0/3                     0          2m18s
lopsided-wildebeest-galaxy-postgres-0                  0/1     CreateContainerConfigError   0          106s
lopsided-wildebeest-galaxy-web-688f57b96-zqhrp         0/1     Init:0/2                     0          2m18s
lopsided-wildebeest-galaxy-web-6c454d48b6-d6b5f        0/1     Running                      0          8d
lopsided-wildebeest-galaxy-web-6c454d48b6-vdrgt        0/1     Running                      0          8d
lopsided-wildebeest-galaxy-web-6c454d48b6-x5mxh        0/1     Running                      0          8d
lopsided-wildebeest-galaxy-workflow-7cfcbf96b5-8br67   1/1     Running                      0          9d
lopsided-wildebeest-galaxy-workflow-7fc6796db7-8d8sn   0/1     Init:0/2                     0          2m18s
```

on inspection, this is probably due to the refactoring of the secret.

```
  Warning  Failed     12s (x4 over 53s)  kubelet, 192.168.0.29  Error: secrets "lopsided-wildebeest-galaxy-secrets" not found
```

Upon these refactoring we should probably produce a new version so that whoever was using 3.2.0 is safe at least on that version.

**Comment by pcm32** [comment]
Upon a new helm install but on top of the same PVCs that were hosting galaxy and postgres (so not deleting the persistent volume claims), all galaxy pods fail to run due to:

```
migrate.versioning.repository DEBUG 2020-02-12 18:50:34,342 [p:6,w:0,m:0] [MainThread] Config: OrderedDict([('db_settings', OrderedDict([('__name__', 'db_settings'), ('repository_id', 'Galaxy'), ('version_table', 'migrate_version'), ('required_dbs', '[]')]))])
Traceback (most recent call last):
  File "/galaxy/server/lib/galaxy/webapps/galaxy/buildapp.py", line 48, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "/galaxy/server/lib/galaxy/app.py", line 92, in __init__
    self._configure_models(check_migrate_databases=self.config.check_migrate_databases, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "/galaxy/server/lib/galaxy/config/__init__.py", line 1146, in _configure_models
    create_or_verify_database(db_url, config_file, self.config.database_engine_options, app=self, map_install_models=combined_install_database)
  File "/galaxy/server/lib/galaxy/model/migrate/check.py", line 35, in create_or_verify_database
    new_database = not database_exists(url)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 484, in database_exists
    return bool(get_scalar_result(engine, text))
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 458, in get_scalar_result
    result_proxy = engine.execute(sql)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2181, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2280, in _wrap_pool_connect
    e, dialect, self
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/galaxy/server/.venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "galaxydbuser"
```

**Comment by pcm32** [comment]
I'm not messing with the database connection in any way in my values file (same values file was working when we merged #107). Any ideas @nuwang ? Thanks!

**Comment by afgane** [comment]
This is an issue with Helm and random passwords that change on upgrade (https://github.com/helm/charts/issues/5167). Until that issue is resolved, we'll have to explicitly set passwords here, which is not being done right now.

**Comment by nuwang** [comment]
Our only option appears to be to simply document this issue. There does not appear to be much interest in providing a good solution to this problem on the Helm side.

**Comment by pcm32** [comment]
Fair enough, so basically for persistent/restartable deployments we just warn that people need to actually set the password for the db, correct?

**Comment by almahmoud** [comment]
I don't think the only solution is for us to just document the issue, unless we are specifically trying to not randomize them (in which case, we should at least make them required...).
We can however just create secrets ourselves for components that are hard dependencies eg: Postgres for Galaxy, and then just use the `existingSecret` feature of the postgres chart to use that password depoyed by the galaxy chart. We can add the helm `pre-install hook` annotations to the secret so it only gets randomized on install, and the Postgres chart values will be set to use that secret. I suggested this on our internal google doc as well, cause I think it would allow us to somewhat uniformly solve this problem for all or at least most secrets in Galaxy and Cloudman. The only restriction is for the child chart to support some version of using existing secrets, which is true for most cases i believe... Unless i'm missing something, this seems like an easy way to accomplish what we want (randomized secrets that the user doesn't have to deal with) with the current Helm design, since it doesn't seem that they're addressing this any time soon on the helm side

**Comment by nuwang** [comment]
@pcm32 Yes, that's what I was thinking.
@almahmoud I looked into the secret option - it's pretty brittle because to make it work, we have to identify every subkey that is being referred to in the secret. This means combing through the third party charts regularly and making sure they don't add any new keys etc. It's not impossible to do, but  it doesn't seems worth the hassle. It's easier from a maintenance perspective to randomize the password in helmsman I think.

**Comment by pcm32** [comment]
Ok, but currently that means creating a secret object and referencing it when spinning up the helm chart. This is probably too convoluted for the average user, we need an easier mechanism for this where you can just set the password in a variable and then that gets injected into a secret and so on...

**Comment by pcm32** [comment]
ahhh, sorry, missed something... I see that it can be set through var... haven't said anything!

**Comment by pcm32** [comment]
https://github.com/galaxyproject/galaxy-helm/commit/22cb428385c95c14822279d07bd58fe7eb45e64b adds this to documentation.
