### ISSUE TITLE
[2.0] Helm upgrade breaks run

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-helm#28]
The following has happened twice (without any other time being succesful):

When attempting to do a helm update, the running Galaxy container fails with:

```
[pid: 561|app: 0|req: 16/29] 172.17.0.1 () {36 vars in 411 bytes} [Wed Sep 12 08:28:18 2018] GET /galaxy/ => generated 47534 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 272 bytes (1 switches on core 3)
172.17.0.1 - - [12/Sep/2018:08:28:24 +0000] "GET /galaxy/ HTTP/1.1" 200 - "-" "kube-probe/1.10"
[pid: 560|app: 0|req: 14/30] 172.17.0.1 () {36 vars in 411 bytes} [Wed Sep 12 08:28:24 2018] GET /galaxy/ => generated 47534 bytes in 11 msecs (HTTP/1.1 200) 3 headers in 272 bytes (1 switches on core 2)
galaxy.queue_worker DEBUG 2018-09-12 08:28:29,152 [p:561,w:2,m:0] [ToolConfWatcher.thread] Executing toolbox reload on 'main.web.2'
Exception in thread ToolConfWatcher.thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "lib/galaxy/tools/toolbox/watcher.py", line 138, in check
  File "lib/galaxy/webapps/galaxy/config_watchers.py", line 24, in <lambda>
  File "lib/galaxy/queue_worker.py", line 92, in reload_toolbox
  File "lib/galaxy/queue_worker.py", line 111, in _get_new_toolbox
  File "lib/galaxy/tools/__init__.py", line 230, in __init__
  File "lib/galaxy/tools/fetcher.py", line 7, in __init__
  File "lib/galaxy/tools/fetcher.py", line 11, in __resolvers_dict
  File "lib/galaxy/util/plugin_config.py", line 18, in plugins_dict
  File "lib/galaxy/util/submodules.py", line 10, in submodules
  File "lib/galaxy/util/submodules.py", line 28, in __submodule_names
OSError: [Errno 2] No such file or directory: 'lib/galaxy/tools/locations'

galaxy.queue_worker DEBUG 2018-09-12 08:28:29,884 [p:560,w:1,m:0] [ToolConfWatcher.thread] Executing toolbox reload on 'main.web.1'
Exception in thread ToolConfWatcher.thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "lib/galaxy/tools/toolbox/watcher.py", line 138, in check
  File "lib/galaxy/webapps/galaxy/config_watchers.py", line 24, in <lambda>
  File "lib/galaxy/queue_worker.py", line 92, in reload_toolbox
  File "lib/galaxy/queue_worker.py", line 111, in _get_new_toolbox
  File "lib/galaxy/tools/__init__.py", line 230, in __init__
  File "lib/galaxy/tools/fetcher.py", line 7, in __init__
  File "lib/galaxy/tools/fetcher.py", line 11, in __resolvers_dict
  File "lib/galaxy/util/plugin_config.py", line 18, in plugins_dict
  File "lib/galaxy/util/submodules.py", line 10, in submodules
  File "lib/galaxy/util/submodules.py", line 28, in __submodule_names
OSError: [Errno 2] No such file or directory: 'lib/galaxy/tools/locations'

172.17.0.1 - - [12/Sep/2018:08:28:30 +0000] "GET /galaxy/ HTTP/1.1" 500 - "-" "kube-probe/1.10"
Error - <class 'mako.exceptions.TemplateLookupException'>: Cant locate template for uri '/js-app.mako'
URL: http://172.17.0.8/galaxy/
File 'lib/galaxy/web/framework/middleware/error.py', line 154 in __call__
File '/export/venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File 'lib/galaxy/web/framework/middleware/statsd.py', line 40 in __call__
File '/export/venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File 'lib/galaxy/web/framework/base.py', line 142 in __call__
File 'lib/galaxy/web/framework/base.py', line 221 in handle_request
File 'lib/galaxy/webapps/galaxy/controllers/root.py', line 111 in index
File 'lib/galaxy/web/base/controller.py', line 324 in template
File 'lib/galaxy/web/framework/webapp.py', line 919 in fill_template
File 'lib/galaxy/web/framework/webapp.py', line 927 in fill_template_mako
File '/export/venv/local/lib/python2.7/site-packages/mako/lookup.py', line 247 in get_template
  return self._check(uri, self._collection[uri])
File '/export/venv/local/lib/python2.7/site-packages/mako/lookup.py', line 349 in _check
  "Cant locate template for uri %r" % uri)
TemplateLookupException: Cant locate template for uri '/js-app.mako'


CGI Variables
-------------
  DOCUMENT_ROOT: '/usr/share/nginx/html'
  HTTP_ACCEPT_ENCODING: 'gzip'
  HTTP_CONNECTION: 'close'
  HTTP_HOST: '172.17.0.8:80'
  HTTP_USER_AGENT: 'kube-probe/1.10'
  PATH_INFO: '/'
  REMOTE_ADDR: '172.17.0.1'
  REMOTE_PORT: '55488'
  REQUEST_METHOD: 'GET'
  REQUEST_URI: '/galaxy/'
  SCRIPT_NAME: '/galaxy'
  SERVER_PORT: '80'
  SERVER_PROTOCOL: 'HTTP/1.1'
  UWSGI_SCHEME: 'http'


WSGI Variables
--------------
  application: <paste.recursive.RecursiveMiddleware object at 0x7fcbfd230990>
  controller_action_key: u'web.root.index'
  is_api_request: False
  paste.cookies: (<SimpleCookie: >, '')
  paste.expected_exceptions: [<class 'paste.httpexceptions.HTTPException'>]
  paste.httpexceptions: <paste.httpexceptions.HTTPExceptionHandler object at 0x7fcbfc3197d0>
  paste.recursive.forward: <paste.recursive.Forwarder from /galaxy>
  paste.recursive.include: <paste.recursive.Includer from /galaxy>
  paste.recursive.include_app_iter: <paste.recursive.IncluderAppIter from /galaxy>
  paste.recursive.script_name: '/galaxy'
  paste.throw_errors: True
  request_id: 'd4301300b66511e8ad210242ac110008'
  uwsgi.core: 1
  uwsgi.node: 'sweet-llama-galaxy-stable-f49b4564f-c9kbn'
  uwsgi.version: '2.0.17'
  webob._parsed_query_vars: (GET([]), '')
  wsgi process: 'Multi process AND threads (?)'
  wsgi.file_wrapper: <built-in function uwsgi_sendfile>
------------------------------------------------------------
```

I reckon that this must be associated to the fact that both new and old Galaxy are looking at the same PVC.

**Comment by nuwang** [comment]
I guess this boils down to the issue that the Galaxy container is currently pushing out code, in addition to data, to the PVC (specifically, the galaxy-central folder containing the source as I recall). That needs to be fixed anyway, so that only data is pushed out, and upgrading becomes a simple matter of swapping out containers?

**Comment by pcm32** [comment]
Totally agree, that is how I used to do it before moving to the docker-stable images. We need a new setup at the level of the docker images used.

**Comment by nuwang** [comment]
Closing because stale and fixed in latest.
